### ISSUE TITLE
站点请求：PO18

### ISSUE THREAD

**Issue by freesialee** [yingziwu/novel-downloader#102]
- 站点名称：PO18
- 站点URL：https://www.po18.tw/
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：有，需挂梯
- 希望添加的理由：有很多热门情欲书籍，比如：
https://www.po18.tw/books/755779
https://www.po18.tw/books/757969

**Comment by yingziwu** [comment]
duplicate #25
