### ISSUE TITLE
长佩文学有锁章文章卡bug

### ISSUE THREAD

**Issue by freesialee** [yingziwu/novel-downloader#123]
您好，长佩文学有锁章的文章如果不筛选掉锁章，无法正常下载，例如：
https://www.gongzicp.com/novel-417183.html
（第13章为锁章）

这种情况可以修复吗？目前可以用筛选章节功能解决，但如果没有提前知道有锁章的话，就得在下载一次发现卡进度之后才能知道然后重新下载。
谢谢！

**Comment by yingziwu** [comment]
我刚想说锁章无法下载这个问题几个月前就发现并且修复了。 d5e839c9f90eb012ec2e4a09c41881ce91de308f

打开你给的链接，发现第13章直接消失不见了。

---------------

用谷歌搜了几本带锁章的书终于摸到了一点门到。

https://www.gongzicp.com/novel-143504.html

长佩有两种锁章，一种锁章是 `lock` 为 `true` ，同时 `chapter_status` 为 `1`  。另外一种锁章是 `lock` 为 `false`，但  `chapter_status`  为 `2` 。

![image](https://user-images.githubusercontent.com/22741471/149753567-857a133b-b299-44fb-abad-445c646eac76.png)

在章节列表中，两种锁章的样式略有不同，上面的那个是 `lock` 为 `true`  的锁章，下面的则是 `chapter_status`  为 `2` 的锁章。

这次修复之后，应该是不存在问题了。
