### ISSUE TITLE
晋江请求更新字库

### ISSUE THREAD

**Issue by sys009** [yingziwu/novel-downloader#136]
最近两天刚看完《开端》电视剧，想再把原著小说看看。
下载下来发现有不少字没识别成功，只显示空白，而且有的字对应也有错误。

**Comment by yingziwu** [comment]
请附上日志

**Comment by sys009** [comment]
> 请附上日志

我记得现在只生成txt以及epub文件，没有日志文件了。
等我明天重下载的时候从浏览器上复制吧。

**Comment by sys009** [comment]
昨天有事没弄，我今天看了一下，好像已经被修复了？
