### ISSUE TITLE
站点请求：米国度

### ISSUE THREAD

**Issue by yingziwu** [yingziwu/novel-downloader#27]
- 站点名称：米国度
- 站点URL：https://www.myrics.com/
- 站点类型：原创网站
- 有无收费章节：有
- 有无如登录墙等额外限制：R18、部分登录墙

**Comment by tiensinh666** [comment]
我已经登录但没出现下载图标。别的站点还能用，只有myrics用不了啊。

**Comment by yingziwu** [comment]
fix on b63aff39a5f0d5981856af03999504dcd3988239
