### ISSUE TITLE
站点请求：次元姬

### ISSUE THREAD

**Issue by HONE13** [yingziwu/novel-downloader#55]
- 站点名称：次元姬
- 站点URL：https://www.ciyuanji.com/
- 站点类型：原创网站
- 有无收费章节：有收费章节
- 有无如登录墙等额外限制：VIP章节需登录
- 希望添加的理由：新兴且小有名气的app，有网站，上面限制比之刺猬猫宽松得多，并且有被刺猬猫的和谐下架的作者在此网站大展身手，是lsp的最后之地，谢谢

**Comment by yingziwu** [comment]
晓夜跑这来了呀！
