### ISSUE TITLE
起点VIP章节下载失败

### ISSUE THREAD

**Issue by sys009** [yingziwu/novel-downloader#69]
已登录账号，已全订章节，记录显示解析成功。
据我个人观察，打开VIP章节的时候是先返回一个空，然后等个两秒才会刷新具体内容。
下载失败的原因大概跟这个有关。

**Comment by yingziwu** [comment]
刚刚在起点多本书上尝试了一下，未能复现。
请提供更多信息。

- 浏览器版本
- 脚本管理器名称及版本 
- 小说下载器是否更新至最新版
- 脚本管理器（TamperMonkey、Violentmonkey）是否为当前浏览器唯一插件
- 小说下载器是否为当前脚本管理器唯一安装脚本
- 出问题的书籍地址
- 具体复现步骤
- 开启deubg模式后的调试日志

**Comment by sys009** [comment]
又多试了几本书，发现几个月前完本的正常下载，最近更新的书下载失败。
如要复现，《神话起源》，《虚拟尽头》，《我的恋爱游戏要满仓》经测试均下载失败。
其实《神话起源》今日刚上架，只有一章付费章节。

**Comment by yingziwu** [comment]
用 `iframe` 简单粗暴的修复了，代价是下载速度大减。

**Comment by yingziwu** [comment]
更加清真的方向，等有空了再做吧。
