### ISSUE TITLE
站点请求：ハーメルン小说网

### ISSUE THREAD

**Issue by bea452awqqw** [yingziwu/novel-downloader#76]
- 站点名称：ハーメルン
- 站点URL：https://syosetu.org
- 站点类型：原创网站 
- 有无收费章节：无
- 有无如登录墙等额外限制：无
- 希望添加的理由：
跟PIXIV一样是日本最大的小说网站之一，该小说网站主要以同人为主，原创为辅，跟国内的菠萝包及刺猬猫小说网类似，希望能添加一下

**Comment by yingziwu** [comment]
刚想说已经在支持列表中，结果仔细一看，之前的是：https://ncode.syosetu.com/
